// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: User.proto

package User

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UserService service

type UserService interface {
	SignIn(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	SignUp(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	UserAction(ctx context.Context, in *ActionRequest, opts ...client.CallOption) (*Response, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "userservice"
	}
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) SignIn(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "UserService.SignIn", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) SignUp(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "UserService.SignUp", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) UserAction(ctx context.Context, in *ActionRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "UserService.UserAction", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	SignIn(context.Context, *Request, *Response) error
	SignUp(context.Context, *Request, *Response) error
	UserAction(context.Context, *ActionRequest, *Response) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) error {
	type userService interface {
		SignIn(ctx context.Context, in *Request, out *Response) error
		SignUp(ctx context.Context, in *Request, out *Response) error
		UserAction(ctx context.Context, in *ActionRequest, out *Response) error
	}
	type UserService struct {
		userService
	}
	h := &userServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&UserService{h}, opts...))
}

type userServiceHandler struct {
	UserServiceHandler
}

func (h *userServiceHandler) SignIn(ctx context.Context, in *Request, out *Response) error {
	return h.UserServiceHandler.SignIn(ctx, in, out)
}

func (h *userServiceHandler) SignUp(ctx context.Context, in *Request, out *Response) error {
	return h.UserServiceHandler.SignUp(ctx, in, out)
}

func (h *userServiceHandler) UserAction(ctx context.Context, in *ActionRequest, out *Response) error {
	return h.UserServiceHandler.UserAction(ctx, in, out)
}
